language: C

os:
  - linux
  - osx
# osx_image: xcode10.2
sudo: required

env:
  global:
    # ANACONDA_TOKEN
    - secure: "doZox+m92r02SdGWU1+Oy7LOc9c/4fRqqoffDDcDC7yAMZZPfx1PIVxxZTyIo8tzLzKQn3VOjIAhC/0HfisI51oKbBbIaJMpLnENgAgCOM43Zg1BLl1rgBFPLabSKWuGgHYZHwUAexLlaiPH5bjUfkCBcLN9MSK8n6yo1kHoY5F0jXLu0Rl5IN4CzwZPLJLY59oVollpC1kYQLntDvzvtvCqXzmxIfQ7fTGCIFGur6ZyBQVisOmOMAAYxnNQ4D3qu0A2bSV6o64cXRl2Uosek8xcscuZjhAlXVwONJHQLSPNLQt9wfRvu7qiZTW0oS0PmYtcy0XcNVh4KuwTjYJGP5f0Knh0LAmnUN6L944XsMShbrbXKIff3T2MPG9Nvi6rtJLE/EmLmyuvY8PbPskHOt6yIH9UhrWAuRQBVjnZIAAE3WSHuf9/abutm7ML5y23vbFnu5VG2KJjCvxKAFm3fbedS4VbkbYKACGFo+f4PbDXbJXMalM0E78j4GQMdSgapRyAbSKLInBIOwNO8+mlktyLBsbphnWJBdXSdU6W31ExObLktg8ApZqrT5U/OvJuXWOWJOYsYTI3j2mx12N4rhA9sT+EWfJklv+TgzUqNQA+feMkK2s97sz3dmzPhJ3xno7y77FzQNBs83x9WHAXDdrPxFbcXNGiep/oRiK6s9w="
  matrix:
    - PYTHON_VERSION=2.7
    - PYTHON_VERSION=3.6
    - PYTHON_VERSION=3.7

install:
  - if [[ $TRAVIS_OS_NAME == 'osx' ]]; then
        wget http://repo.continuum.io/miniconda/Miniconda3-latest-MacOSX-x86_64.sh -O miniconda.sh;
    else
        wget http://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh;
    fi
  - bash miniconda.sh -b -p $HOME/miniconda
  - source $HOME/miniconda/bin/activate
  - conda config --set always_yes yes --set changeps1 no --set auto_update_conda no
  - conda install conda conda-verify conda-build anaconda-client numpy
  - conda info -a
  # Add MKL shared libraries (for MKL pardiso) to the path
  - |
    MKL_PARDISO_LIB_DIR=`python -c 'import numpy.distutils.system_info as sysinfo; print(sysinfo.get_info("mkl")["library_dirs"][0])'`
    if [[ "${TRAVIS_OS_NAME}" == "linux" ]]; then
        export LD_LIBRARY_PATH=${LD_LIBRARY_PATH}$:{MKL_PARDISO_LIB_DIR}
    # else if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then
    #     # export DYLD_LIBRARY_PATH=${DYLD_LIBRARY_PATH}:${MKL_PARDISO_LIB_DIR}
    # fi
    fi

script:
  # Build and test conda
  - conda build conda-recipe --python=$PYTHON_VERSION --output-folder conda-bld

  # Get OSQP version (for later packaging)
  - export OSQP_VERSION=`python setup.py --version`
  # Different anaconda label for dev/release versions
  - if [[ ${OSQP_VERSION} == *"dev"* ]]; then export ANACONDA_LABEL="dev"; else export ANACONDA_LABEL="main"; fi
        

deploy:
  # Anaconda
  - provider: script
    script: anaconda -t $ANACONDA_TOKEN upload ${TRAVIS_BUILD_DIR}/conda-bld/**/*.tar.bz2 --user oxfordcontrol --force -l ${ANACONDA_LABEL}
    skip_cleanup: true
    on:
      all_branches: true
    #   tags: true
