platform:
  - x64
  - x86

environment:
  ANACONDA_TOKEN:
    secure: H1vdxUBNWGzvvbIyuuVByqh4zHV/VO2GI090QaQgG8En49Jks4N6yOGe6+m7cZEH
  matrix:
    - PYTHON_VERSION: 2.7
    - PYTHON_VERSION: 3.6
    - PYTHON_VERSION: 3.7

init:
  # Uncomment for remote desktop debug
  # - ps: iex ((new-object net.webclient).DownloadString('https://raw.githubusercontent.com/appveyor/ci/master/scripts/enable-rdp.ps1'))
  - ECHO %PYTHON_VERSION% %MINICONDA%

# Not a .NET project. We build it in the install script
build: false

install:
  - git submodule update --init --recursive
    # Setup 32 bit
  - if "%PLATFORM%"=="x86" set MINICONDA=C:\Miniconda3
  - if "%PLATFORM%"=="x64" set MINICONDA=C:\Miniconda3-x64
  - ECHO %MINICONDA%
  - call %MINICONDA%\Scripts\activate
  - conda.exe config --append channels conda-forge
  - conda.exe install conda conda-verify conda-build=3.17.8 anaconda-client vs2008_express_vc_python_patch --yes
    # Fix for 64-bit Python 2.7 builds, courtesy vs2008_express_vc_python_patch
  - call %MINICONDA%\Scripts\setup_x64.bat
  - conda.exe info -a

test_script:
  - call conda.exe build --python %PYTHON_VERSION% conda-recipe --output-folder conda-bld


deploy_script:
  - "%APPVEYOR_BUILD_FOLDER%\\ci\\appveyor\\deploy.cmd"
  
# on_finish:
#   # Uncomment for remote desktop debug
#   - ps: $blockRdp = $true; iex ((new-object net.webclient).DownloadString('https://raw.githubusercontent.com/appveyor/ci/master/scripts/enable-rdp.ps1'))
