jobs:

- job: 'test_linux'
  # strategy:
  #   matrix:
  #     linux:
  #       imageName: 'ubuntu-16.04'
  #     mac:
  #       imageName: 'macos-10.13'
  #     windows:
  #       imageName: 'vs2017-win2016'

  pool:
    vmImage: 'ubuntu-16.04'

  strategy:
    matrix:
      Python27:
        PYTHON_VERSION: '2.7'
      Python35:
        PYTHON_VERSION: '3.5'
      Python36:
        PYTHON_VERSION: '3.6'
      Python37:
        PYTHON_VERSION: '3.7'
    maxParallel: 4

  steps:
    - script: |
        conda config --set always_yes yes --set changeps1 no --set auto_update_conda no
        conda build conda-recipe --python=$PYTHON_VERSION
      displayName: 'Create and test conda recipe'


  # steps:
  # - task: UsePythonVersion@0
  #   inputs:
  #     versionSpec: '$(python.version)'
  #     architecture: 'x64'
  #
  # - script: python -m pip install --upgrade pip && pip install -r requirements.txt
  #   displayName: 'Install dependencies'
  #
  # - script: |
  #     pip install pytest
  #     pytest tests --doctest-modules --junitxml=junit/test-results.xml
  #   displayName: 'pytest'
  #
  # - task: PublishTestResults@2
  #   inputs:
  #     testResultsFiles: '**/test-results.xml'
  #     testRunTitle: 'Python $(python.version)'
  #   condition: succeededOrFailed()

# - job: 'Publish'
#   dependsOn: 'Test'
#   pool:
#     vmImage: 'Ubuntu-16.04'
#
#   steps:
#   - task: UsePythonVersion@0
#     inputs:
#       versionSpec: '3.x'
#       architecture: 'x64'
#
#   - script: python setup.py sdist
#     displayName: 'Build sdist'
#
